version: '3.7'
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: '${INTEGRATION_TEST_TIMEOUT}'

  nestbox:
    image: nginx
    ports:
      - '443'
    volumes:
      - ./etc/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf:ro
      - ./ssl:/usr/local/share/ssl:ro
    depends_on:
      - nestbox-auth
      - nestbox-deployd

  nestbox-auth:
    image: wazoplatform/wazo-auth-mock
    ports:
      - '9497'

  nestbox-deployd:
    image: wazoplatform/wazo-deployd-mock
    ports:
      - '9800'
    command: /usr/local/bin/wazo-deployd-mock.py 9800

  auth:
    image: wazoplatform/wazo-auth-mock
    ports:
      - '9497'

  confd:
    image: wazoplatform/wazo-confd-mock
    ports:
      - '9486'

  setupd:
    image: wazo-setupd-test
    environment:
      XIVO_UUID: cd030e68-ace9-4ad4-bc4e-13c8dec67898
    volumes:
      - ../..:/usr/src/wazo-setupd:ro
      - ./etc/wazo-setupd/conf.d/50-default-config.yml:/etc/wazo-setupd/conf.d/50-default-config.yml:ro
      - ./keys/wazo-setupd-key.yml:/var/lib/wazo-auth-keys/wazo-setupd-key.yml:ro
      # - '${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.7/site-packages/xivo'
    ports:
      - '9302'

  sysconfd:
    image: wazoplatform/wazo-sysconfd-mock
    ports:
      - '8668'

  webhookd:
    image: wazoplatform/wazo-webhookd-mock
    ports:
      - '9300'
    command: /usr/local/bin/wazo-webhookd-mock.py 9300
